### PR TITLE
style: prefer double quotes to single quotes

### PR DESCRIPTION
**Pull request by rememberYou**
This pull request replace single quotes with double quotes to have a more consistent and readable code.

According to [black](https://github.com/psf/black/tree/537ea8df35b1004bdb228b483907fb5dd92e5257) Python code formatter:

> Why settle on double quotes? They anticipate apostrophes in English text. They match the docstring standard described in PEP 257. An empty string in double quotes ("") is impossible to confuse with a one double-quote regardless of fonts and syntax highlighting used. On top of this, double quotes for strings are consistent with C which Python interacts a lot with.

**Source:** https://github.com/psf/black/blob/537ea8df35b1004bdb228b483907fb5dd92e5257/docs/the_black_code_style.md#strings

### CODE REVIEW

**Comment by GillesVandewiele** [comment]
Hi @rememberYou 

Sorry for my later replies. I was on holidays until now. I will go through your PRs one by one. Many thanks for this!

I can agree with your argumentation, and I'm all for this change. One thing we should perhaps first put in order is either something that automatically checks on PEP-8 & custom rules (such as this one) for every commit that is done. This could perhaps also be done automatically (not sure if replacing single by double quotes can ever break something except when nesting). I think that is important because I will probably still make the mistake of using single quotes. The reason I use that one over the double is that I don't need to press SHIFT for single quotes on a QWERTY.

**Comment by rememberYou** [comment]
That's a good point.

To add more consistent coding styles, we could add an `.editorconfig` file, this would help each text/IDE editor to adapt to the rules defined in it. Unfortunately, [EditorConfig](https://editorconfig.org/) does not yet have a rule to enforce the use of double quotes rather than single quotes.

What we can do from a commits point of view is to add `black` as pre-commit autoformatting tool, this would keep a consistent code on the repository 😊

If it seems correct to you, I can make two pull requests to add these recommendations.

**Comment by GillesVandewiele** [comment]
That would be great @rememberYou 

If you don't have any time, we can always open an issue as well and close this PR for now.

**Comment by rememberYou** [comment]
I'm going to add the pull requests today. That way, you will can also merge this one and don't have to worry about the quotes anymore :-)

**Comment by rememberYou** [comment]
@GillesVandewiele should we merge this?

**Comment by GillesVandewiele** [comment]
Yes please! Go ahead :)

**Pull request merged**
