### PR TITLE
feat: add pre-commit

### PR DESCRIPTION
**Pull request by rememberYou**
This pull request will add [pre-commit](https://github.com/pre-commit/pre-commit) for managing pre-commit hooks.

This makes it possible to check each file when the user commits and ensure that each commit follows the imposed coding styles of `pyRDF2Vec`.

**More information:** https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/

For the added hooks:
- `black`: to format the python code;
- `flake8`:  to check the code’s compliance to PEP8;
- `isort`: to sort Python imports;
- `pyupgrade`: to automatically upgrade syntax for newer versions of the language.

### CODE REVIEW

**Comment by GillesVandewiele** [comment]
Hi @rememberYou,

Does this work automatically? I.e. does `git` automatically discover the necessary files and executes them every time someone runs `git commit` on his command line, or does this need to be set by the devs locally too? If it requires some local set-up I might make a wiki-page where we explain some of the good practices (i.e. use the editorconfig file, make sure these pre-commit hooks are enabled, and so on).

**Comment by rememberYou** [comment]
The `pre-commit `package is on the [requirements](https://github.com/IBCNServices/pyRDF2Vec/blob/master/requirements.txt) file of this pull request, but not on the [setup.py](https://github.com/IBCNServices/pyRDF2Vec/blob/master/setup.py) one.

Thus, this package will be installed as dependencies only for developers who wish to contribute to `pyRDF2Vec`. However, to use it, developers must install Git hooks using the command: `pre-commit install`

Then, on each commit, all the necessary files from `pyRDF2vec` will be checked to make sure the coding styles are good. The downside of this pre-commit is that it can take a few seconds. 

Ideally, only files modified by the developer should be checked, but I haven't found an efficient way to do this.

**Comment by GillesVandewiele** [comment]
Ok great! I'll make a quick wiki page (which we can then extend in the future) and then merge these :).

**Comment by rememberYou** [comment]
Maybe, it would be more appropriate to use `CONTRIBUTING.md` file.

**Pull request merged**
